<a href="https://colab.research.google.com/github/Muhammad-Waleed-Source/Pandas/blob/main/Pandas_6_MultiIndex_Series_and_DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

### Series is 1D and DataFrames are 2D objects

- But why?
- And what exactly is index?

# **1. Multi-index Series**

In [55]:
# can we have multiple index? Let's try
index_val = [('cse',2019), ('cse', 2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]

a = pd.Series([1, 2, 3, 4, 5, 6, 7, 8], index=index_val)

print(a)

(cse, 2019)    1
(cse, 2020)    2
(cse, 2021)    3
(cse, 2022)    4
(ece, 2019)    5
(ece, 2020)    6
(ece, 2021)    7
(ece, 2022)    8
dtype: int64
<class 'pandas.core.series.Series'>

In [6]:
print(a[('cse', 2021)])

3

In [54]:
# The Problem? (What if we want to fetch all the values where the index is cse)

a['cse'] # this will give error

KeyError: 'cse'

So the above method is not good to create a multi-index series.

In [ ]:
# The solution -> multiindex series(also known as Hierarchical Indexing)
# multiple index levels within a single index

In [8]:
# how to create multiindex object

# 1. pd.MultiIndex.from_tuples()
index_val = [('cse',2019), ('cse', 2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]

multiindex = pd.MultiIndex.from_tuples(index_val)
print(multiindex)

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [9]:
# So pandas will decouple the indexes, let's see
print(multiindex.levels)

[['cse', 'ece'], [2019, 2020, 2021, 2022]]

In [11]:
# 2. pd.MultiIndex.from_product(). **Best way**

pd.MultiIndex.from_product([['cse', 'ece'], [2019, 2020, 2021, 2022]])

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [15]:
# Creating a series with multi-index object
s = pd.Series([1,2,3,4,5,6,7,8], index=multiindex)

In [17]:
# How to fetch items from such series
print(s['cse'])

2019    1
2020    2
2021    3
2022    4
dtype: int64

In [19]:
print(s['ece'])

2019    5
2020    6
2021    7
2022    8
dtype: int64

In [20]:
print(s[('cse', 2021)])

3

So multi-index series is 2D because we need two thing to fetch a specific record, whereas for a 1D series we need only one thing.

In [57]:
# unstack (convertind a multi-index series to a dataframe)

temp = s.unstack().reset_index()
print(temp)

  index  2019  2020  2021  2022
0   cse     1     2     3     4
1   ece     5     6     7     8

In [49]:
# Three ways to access items from a dataframe
print(temp.loc['cse', 2019])
print(temp.iloc[0, 0])
print(temp.at['cse', 2019])

1
1
1

In [43]:
print(temp.loc['ece', 2019])
print(temp.iloc[1, 0])
print(temp.at['ece', 2019])

5
5
5

In [45]:
# stack (Opposite of unstack, converts a dataframe into a multi-index series)

print(temp.stack()) # Got the original thing back

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

## **Question:**
Why we need a multi-index series if we can display the data using dataframe?

## **Answer:**
We can display a higher dimension data like 3D, 4D or 10D etc into a lower dimension data like 2D using two lower dimension objects called series and dataframe.

# **2. Multi-index Dataframe**

In [58]:
multiindex

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [59]:
branch_df1 = pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12],
        [13,14],
        [15,16],
    ],
    index = multiindex,
    columns = ['avg_package','students']
)

print(branch_df1)

# So here basically we presented our 3D data in a 2D dataframe

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [61]:
print(branch_df1.loc['cse'])

      avg_package  students
2019            1         2
2020            3         4
2021            5         6
2022            7         8

In [71]:
print(branch_df1.loc['ece'])

      avg_package  students
2019            9        10
2020           11        12
2021           13        14
2022           15        16

In [67]:
print(branch_df1['avg_package']) # multi-index series

cse  2019     1
     2020     3
     2021     5
     2022     7
ece  2019     9
     2020    11
     2021    13
     2022    15
Name: avg_package, dtype: int64

In [68]:
print(branch_df1['students']) # multi-index series

cse  2019     2
     2020     4
     2021     6
     2022     8
ece  2019    10
     2020    12
     2021    14
     2022    16
Name: students, dtype: int64

In [72]:
# multiindex df from columns perspective
branch_df2 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
    ],
    index = [2019,2020,2021,2022],
    columns = pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)

branch_df2

           delhi               mumbai
     avg_package students avg_package students
2019           1        2           0        0
2020           3        4           0        0
2021           5        6           0        0
2022           7        8           0        0

In [73]:
branch_df2['delhi']

      avg_package  students
2019            1         2
2020            3         4
2021            5         6
2022            7         8

In [74]:
branch_df2['mumbai']

      avg_package  students
2019            0         0
2020            0         0
2021            0         0
2022            0         0

In [75]:
branch_df2['mumbai']['avg_package']

2019    0
2020    0
2021    0
2022    0
Name: avg_package, dtype: int64

In [80]:
# extracting rows
branch_df2.loc[2019]

delhi   avg_package    1
        students       2
mumbai  avg_package    0
        students       0
Name: 2019, dtype: int64